<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 3/5/2018
 * Time: 8:18 PM
 */

class M_inventory extends MY_Model
{
    protected $_table_name  = 'n_inventory';
    protected $_timestamps  = TRUE;

    function get_new_data(){
        $inventory = new stdClass();
        $inventory->sale1 = 0;
        $inventory->sale2 = 0;
        $inventory->sale3 = 0;
        $inventory->cost1 = 0;
        $inventory->cost2 = 0;
        $inventory->cost3 = 0;
        $inventory->cost_supplier = 0;
        $inventory->cost_distributor = 0;
        $inventory->qty1 = 0;
        $inventory->qty2 = 0;
        $inventory->qty3 = 0;
        $inventory->qty4 = 0;
        $inventory->qty5 = 0;
        $inventory->qty_limit = 0;
        $inventory->location = '';
        $inventory->is_active = 'checked';
        $inventory->is_order = '';
        return $inventory;
    }

    function get_statistik(){
        $this->db->select('
            MAX(modified) AS `update`,
            COUNT(*) AS total_product,
            (SELECT COUNT(*) AS total_active FROM ' . $this->_table_name . ' WHERE is_active IS NOT NULL) AS active_product,
            ((SELECT COUNT(*) AS total_active FROM ' . $this->_table_name . ' WHERE is_active IS NOT NULL) / COUNT(*) * 100) AS percent_product
        ');
        return $this->db->get($this->_table_name)->row();
    }


    public function get($id = NULL, $single = FALSE)
    {
        $table1_join = 'n_product';
        $field1_join = 'n_inventory.n_product_id = n_product.id';

        $this->db->select(" " . $this->_table_name . ".id,
                            `code`,
                            " . $this->_table_name . ".created,
                            " . $this->_table_name . ".modified,
                            sale1,
                            sale2,
                            sale3,
                            cost1,
                            cost2,
                            cost3,
                            cost_supplier,
                            cost_distributor,
                            qty1,
                            qty2,
                            qty3,
                            qty4,
                            qty5,
                            qty_limit,
                            location,
                            " . $this->_table_name . ".is_active,
                            " . $this->_table_name . ".is_order,
                            " . $table1_join . ".`name`,
                            " . $table1_join . ".description,
                            " . $table1_join . ".is_stock_tracking,
                            " . $table1_join . ".path,
                            " . $table1_join . ".barcode ");
        $this->db->join($table1_join, $field1_join, 'INNER');

        return parent::get($id, $single); // TODO: Change the autogenerated stub
    }
}