<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 3/2/2018
 * Time: 12:34 AM
 */

class M_product extends MY_Model
{
    protected $_table_name = 'n_product';
    protected $_timestamps = TRUE;

    public function get_new_data(){
        $product = new stdClass();
        $product->name              = '';
        $product->description       = '';
        $product->barcode           = date('ymd') . $this->get_id();
        $product->is_active         = '';
        $product->is_order          = '';
        $product->is_stock_tracking = '';
        $product->n_supplier_id     = '';
        return $product;
    }

    public function get($id = NULL, $single = FALSE)
    {
        $this->db->select(array('id',
            '`name`',
            'description',
            'barcode',
            'is_active',
            'is_order',
            'is_stock_tracking',
            'created',
            'modified',
            'n_supplier_id',
            'path'));
        return parent::get($id, $single); // TODO: Change the autogenerated stub
    }

    public function get_by($where, $single = FALSE)
    {
        $this->db->select(array('id',
            '`name`',
            'description',
            'barcode',
            'is_active',
            'is_order',
            'is_stock_tracking',
            'created',
            'modified',
            'n_supplier_id',
            'path'));
        return parent::get_by($where, $single); // TODO: Change the autogenerated stub
    }

    public function get_id(){
        $this->db->select('MAX(id) AS id');
        return $this->db->get($this->_table_name)->row()->id + 1;
    }

    function get_statistik(){
        $this->db->select('
            MAX(modified) AS `update`,
            COUNT(*) AS total_product,
            (SELECT COUNT(*) AS total_active FROM ' . $this->_table_name . ' WHERE is_active IS NOT NULL) AS active_product,
            ((SELECT COUNT(*) AS total_active FROM ' . $this->_table_name . ' WHERE is_active IS NOT NULL) / COUNT(*) * 100) AS percent_product
        ');
        return $this->db->get($this->_table_name)->row();
    }
}