<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 3/10/2018
 * Time: 1:27 AM
 */

class M_store extends MY_Model
{
    protected $_table_name = "n_store";
    protected $_timestamps = TRUE;

    public function get($id = NULL, $single = FALSE)
    {
        $this->db->where('is_warehouse !=', 'checked');
        return parent::get($id, $single); // TODO: Change the autogenerated stub
    }

    public function get_new_data(){
        $store = new stdClass();
        $store->code = 'SPLC' . date('ymd') . $this->get_id();
        $store->name = "Store Name";
        $store->email = "email@domain.com";
        $store->phone = "0000";
        $store->fax = "0000";
        $store->is_active = "checked";
        $store->is_warehouse = "checked";
        $store->show_other_stock = "checked";
        $store->mata_uang = "Rp. ";
        $store->area = "Area Toko";
        $store->alamat = "Alamat Toko";
        return $store;
    }

    public function get_id(){
        $this->db->select('MAX(id) AS id');
        return $this->db->get($this->_table_name)->row()->id + 1;
    }
}