<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 3/17/2018
 * Time: 3:17 AM
 */

class M_logis_indata_detail extends MY_Model
{
    protected $_table_name = 'n_stock_order_detail';

    public function get_by($where, $single = FALSE)
    {
        $this->db->select("*, n_stock_order_detail.id AS id_cart, n_inventory.id AS id_inv");
        $this->db->join("n_inventory", "n_inventory.id = n_stock_order_detail.product_id", "INNER");
        $this->db->join("n_product", "n_inventory.n_product_id = n_product.id", "INNER");
        return parent::get_by($where, $single); // TODO: Change the autogenerated stub
    }
}